server:
  port: 8080

zuul:
  routes:
    auth-register:
      path: /register/**
      url: http://127.0.0.1:8088/
      sensitiveHeaders: Cookie,Set-Cookie
      stripPrefix: false
    auth-center:
      path: /login/**
      url: http://127.0.0.1:8088/
      sensitiveHeaders: Cookie,Set-Cookie
      stripPrefix: false
    backend-service:
      path: /backend/**
      url: http://127.0.0.1:8082/
      sensitiveHeaders: Cookie,Set-Cookie
      stripPrefix: false

